# jobs starting with "." are ignored by gitlab-ci, they are used as anchor, which
# enable to reuse the same code inside multiple jobs. Please see YAML specification
# for more information
.unix_get_superbuild:
  script: &unix_get_superbuild
    - cd ..
    - chmod +x ${CI_PROJECT_DIR}/CI/findRightSuperbuildCache.sh
    - ${CI_PROJECT_DIR}/CI/findRightSuperbuildCache.sh ${OS} ${CI_COMMIT_REF_NAME} ${MINIO_CACHE_SERVER_ADDRESS} ${MINIO_CACHE_SERVER_ACCESS_KEY} ${MINIO_CACHE_SERVER_SECRET_KEY} ${mode}
    # create a symbolic link
    - cd ${CI_PROJECT_DIR}
    - ln -s ../Superbuild-build Superbuild-build

# this removes previous superbuild build files
.superbuild_remove_old_dir:
  script: &superbuild_remove_old_dir
  - rm -rf ../Superbuild-build/

.linux_superbuild: &linux_superbuild
  stage: superbuild
  before_script: *superbuild_remove_old_dir
  script:
    - git submodule sync
    - git submodule update --init --recursive
    # prepare directory
    - cd ..
    - mkdir -p Superbuild-build/
    - cd Superbuild-build/
    # configure & generate
    - >
      if [ "${mode}" == "full" ]; then
        optional_dependancies="ON"
      else
        optional_dependancies="OFF"
      fi
    - cmake -DCMAKE_BUILD_TYPE:STRING=${cmake_option_CMAKE_BUILD_TYPE}
      -DBUILD_TESTING=True
      -DENABLE_all=${optional_dependancies}
      -Dsuperbuild_download_location="../downloads"
      ${CI_PROJECT_DIR}/Superbuild
    # disable darknet on CI because no GPU available
    - cmake -DENABLE_all=False -DENABLE_darknet=False .
    # force pcl to build only with 3 thread because we don't have enough RAM
    - >
      if [ "${mode}" == "full" ]; then
        cmake -DSUPERBUILD_PROJECT_PARALLELISM=3 .
        make pcl -j8
        cmake -DSUPERBUILD_PROJECT_PARALLELISM=$(nproc) .
      fi
    # compile
    - make -j8
    # remove lidarview
    - rm -rf lidarview-superbuild/common-superbuild/lidarview
    # upload superbuild, Apple's Zip Utility, which I guess is use by gilab-ci
    # produce corrupted file for large file, so we need to upload the cache manually
    - cd ..
    - echo "compressing and uploading Superbuild. This take some time..."
    - tar zcf archive Superbuild-build/
    - ~/mc config host add superbuild ${MINIO_CACHE_SERVER_ADDRESS} ${MINIO_CACHE_SERVER_ACCESS_KEY} ${MINIO_CACHE_SERVER_SECRET_KEY}
    - ~/mc cp archive superbuild/runner/minio/project/808/${cache_patch}/${OS}/${CI_COMMIT_REF_NAME}-${mode}

.linux_superbuild_manual: &linux_superbuild_manual
  when: manual
  <<: *linux_superbuild
  stage: manual

.linux_superbuild_schedule: &linux_superbuild_schedule
  <<: *linux_superbuild
  only:
    - schedules

.unix_build: &unix_build
  stage: build
  extends: .only-important
  before_script: *unix_get_superbuild
  script:
    - git submodule sync
    - git submodule update --init --recursive
    - cd ../Superbuild-build/ # created by extracting cache in "unix_get_superbuild"
    - make lidarview -j8

.unix_test: &unix_test
  stage: test
  extends: .only-important
  before_script: *unix_get_superbuild # you cannot put unix_build here
  script:
    # get test data and baseline
    - git submodule sync
    - git submodule update --init --recursive
    - git submodule update --init TestData
    - cd ../Superbuild-build/ # created by extracting cache in "unix_get_superbuild"
    - make lidarview -j8
    - cd ../Superbuild-build/lidarview-superbuild/common-superbuild/lidarview/build
    - cmake . -DBUILD_TESTING=True
    - make -j8
    # excluding packaging test targets (packaging is done later)
    # TODO current Source related tests fails, so we skip them.
    # This need to be fixed !
    - ctest -E "$test_blacklist"

.unix_package: &unix_package
  stage: package
  before_script: *unix_get_superbuild # you cannot put unix_build here
  script:
    - git submodule sync
    - git submodule update --init --recursive
    - cd ../Superbuild-build/ # created by extracting cache in "unix_get_superbuild"
    - make lidarview -j8
    - ctest -R cpack
#    - ctest -R cpack-lidarview-TGZ -V

.unix_package_manual: &unix_package_manual
  when: manual
  <<: *unix_package
  stage: manual
  artifacts:
    name: ${CI_JOB_NAME}-${mode}
    paths:
     - Superbuild-build/*.tar.gz
     - Superbuild-build/*.dmg
    expire_in: 3 day

.unix_package_schedule: &unix_package_schedule
  <<: *unix_package
  artifacts:
    name: ${CI_JOB_NAME}-${mode}
    paths:
     - Superbuild-build/*.tar.gz # Superbuild-build links to ../Superbuild-build
     - Superbuild-build/*.dmg
    expire_in: 7 day
  only:
    - schedules

#-------------------------------------------------------------------------------
# jobs for Ubuntu 16.04
#-------------------------------------------------------------------------------
.ubuntu_16_04: &ubuntu_16_04
  tags:
    - ubuntu_16.04
  variables:
    OS: ubuntu_16.04

ubuntu16.04_build:
  <<: *ubuntu_16_04
  <<: *unix_build

ubuntu16.04_test:
  <<: *ubuntu_16_04
  <<: *unix_test

# For SuperBuild and package
# the "mode" variable should be used for choosing light/full
ubuntu16.04_superbuild_manual:
  <<: *ubuntu_16_04
  <<: *linux_superbuild_manual

ubuntu16.04_superbuild_schedule:
  <<: *ubuntu_16_04
  <<: *linux_superbuild_schedule

ubuntu16.04_package_manual:
  <<: *ubuntu_16_04
  <<: *unix_package_manual

ubuntu16.04_package_schedule:
  <<: *ubuntu_16_04
  <<: *unix_package_schedule
