# this cmake variable are exposed here so schedule jobs can modify them
variables:
  # cmake superbuild option
  cmake_option_ENABLE_veloview: "True"
  cmake_option_USE_SYSTEM_python: "True"
  cmake_option_CMAKE_BUILD_TYPE: "Release"

# this are the 4 stage of the continuous integration, the stage are executed one after another
stages:
  - superbuild
  - build
  - test
  - package

# jobs starting with "." are ignored by gitlab-ci, they are used as anchor, which 
# enable to reuse the same code inside multiple jobs. Please see YAML specification
# for more information
.default-cache: &default-cache
  key: ${OS}-${CI_COMMIT_REF_NAME}
  paths:
    - Superbuild-build

.push-cache: &push-cache
  cache:
    <<: *default-cache
    policy: push

.pull-cache: &pull-cache
  cache:
    <<: *default-cache
    policy: pull

################################################################################
### anchor jobs for linux, they will be used accros multiple other jobs
### WARNING do not declare variable as they will overwrite all other variable!!!
################################################################################

.linux_get_superbuild:
  script: &linux_get_superbuild
    - chmod +x CI/findRightSuperbuildCache.sh
    - CI/findRightSuperbuildCache.sh ${OS} ${CI_COMMIT_REF_NAME} ${MINIO_CACHE_SERVER_ADDRESS} ${MINIO_CACHE_SERVER_ACCESS_KEY} ${MINIO_CACHE_SERVER_SECRET_KEY}

.linux_superbuild: &linux_superbuild
  stage: superbuild
  script:
    # prepare directory
    - mkdir Superbuild-build/
    - cd Superbuild-build/
    # configure & generate
    - cmake -DCMAKE_BUILD_TYPE:STRING=${cmake_option_CMAKE_BUILD_TYPE}
      -DENABLE_veloview:BOOL=${cmake_option_ENABLE_veloview}
      -DUSE_SYSTEM_python:BOOL=${cmake_option_USE_SYSTEM_python}
      ${CI_PROJECT_DIR}/Superbuild
    # compile
    - make -j8
    # remove Veloview
    - rm -rf veloview/
  <<: *push-cache

.linux_superbuild_manual: &linux_superbuild_manual
  when: manual
  <<: *linux_superbuild

.linux_superbuild_schedule: &linux_superbuild_schedule
  <<: *linux_superbuild
  only:
    - schedules

.linux_build: &linux_build
  stage: build
  before_script: *linux_get_superbuild
  script:
    - cd Superbuild-build/
    - make veloview -j8
  artifacts:
    paths:
     - Superbuild-build/veloview
    expire_in: 24 hr

.linux_test: &linux_test
  stage: test
  before_script: *linux_get_superbuild
  script:
    # get test data and baseline
    # DO NOT use gilab-ci variable GIT_SUBMODULE_STRATEGY !!!
    - git submodule update --init --recursive
    - cd Superbuild-build/veloview/src/veloview-build
    - cmake -DBUILD_TESTING:BOLL=True
      ${CI_PROJECT_DIR}
    - make -j8
    - ctest

.linux_package: &linux_package
  stage: package
  before_script: *linux_get_superbuild
  script:
    - cd Superbuild-build
    - make package -j8

.linux_package_manual: &linux_package_manual
  when: manual
  <<: *linux_package
  artifacts:
    name: ${CI_JOB_NAME}
    paths:
     - Superbuild-build/*.tar.gz
    expire_in: 1 hr

.linux_package_schedule: &linux_package_schedule
  <<: *linux_package
  artifacts:
    name: ${CI_JOB_NAME}
    paths:
     - Superbuild-build/*.tar.gz
    expire_in: 1 day
  only:
    - schedules

#-------------------------------------------------------------------------------
# jobs for ubunu 16.04
#-------------------------------------------------------------------------------
.ubuntu_16_04: &ubuntu_16_04
  tags:
    - ubuntu_16.04
  variables:
    OS: ubuntu_16.04

ubuntu16.04_superbuild_manual:
  <<: *ubuntu_16_04
  <<: *linux_superbuild_manual

ubuntu16.04_superbuild_schedule:
  <<: *ubuntu_16_04
  <<: *linux_superbuild_schedule

ubuntu16.04_build:
  <<: *ubuntu_16_04
  <<: *linux_build

ubuntu16.04_test:
  <<: *ubuntu_16_04
  <<: *linux_test

ubuntu16.04_package_manual:
  <<: *ubuntu_16_04
  <<: *linux_package_manual

ubuntu16.04_package_schedule:
  <<: *ubuntu_16_04
  <<: *linux_package_schedule

#-------------------------------------------------------------------------------
# jobs for ubunu 14.04.5
#-------------------------------------------------------------------------------
.ubuntu_14_04_5: &ubuntu_14_04_5
  tags:
    - ubuntu_14.04.5
  variables:
    OS: ubuntu_14.04.5
  only:
    - schedules

ubuntu14.04.5_superbuild_schedule:
  <<: *ubuntu_14_04_5
  <<: *linux_superbuild_schedule

ubuntu14.04.5_build:
  <<: *ubuntu_14_04_5
  <<: *linux_build

ubuntu14.04.5_test:
  <<: *ubuntu_14_04_5
  <<: *linux_test

ubuntu14.04.5_package_schedule:
  <<: *ubuntu_14_04_5
  <<: *linux_package_schedule
